### ISSUE TITLE
Energydata task list

### ISSUE THREAD

**Issue by derwas** [derilinx/derilinx#29]
From ckan-docker created by [jodiegardiner](https://github.com/jodiegardiner) : derilinx/ckan-docker#284  

## Setup & Core work
 - [x] S3 bucket copied
 - [x] Our own s3 bucket populated
 - [ ] Linode firewall?
 - [x] make sure geojson goes thru tippecanoe to S3 - MVT extension
 - [ ] check and implement other jobs/cron/harvesting etc
 - [x] file and repo structure

## Functionality testing
 - [x] create a dataset
 - [x] then add a resource - filestore and datastore
 - [x] create org
 - [x] upload org image
 - [x] add dataset via org
 - [x] csv previews work
 - [x] geojson previews work

## Pre launch
 - [x] Pagination looks bad
 - [x] Wider UI pass
 - [ ] create production server
 - [ ] take off basic auth
 - [ ] enable ssl again
 - [ ] point dns at Linode ip
 - [ ] Launch!
## Post launch
 - [ ] Fun weekend
