### ISSUE TITLE
DGI3 Release Checklist

### ISSUE THREAD

**Issue by derwas** [derilinx/derilinx#93]
From ckan-docker created by [CarlQLange](https://github.com/CarlQLange) : derilinx/ckan-docker#278  

- [x] install docker, docker-compose etc.
- [x] ./build.sh
- [x] get user list from dgi2 following steps here: https://github.com/derilinx/ckanext-dgithree/wiki/User-migration-from-DGI2
- [x] `dce ckan env DGI2API="" DGI2HOST="https://85.90.246.245" ORGS=1 USERS=1 PAGES=0 DATAREQUESTS=0 SHOWCASES=0 DATASETS=0 OPENSTANDARDS=0 /usr/lib/ckan/default/bin/paster --plugin=ckanext-dgithree scripted_harvesters dgitwo --config=/etc/ckan/default/ckan.ini`
  - you need to create users as sysadmins manually using paster sysadmin add (will spit out users to make sysadmins)
  - you need to add CSO admin/members manually since the `org_show` action takes a million years on dgi2
- [x] get pages from dgi2 following steps here: https://github.com/derilinx/ckanext-dgithree/wiki/Page-Blog-migration-from-DGI2
- [x] `dce ckan env DGI2API="" DGI2HOST="https://85.90.246.245" ORGS=0 USERS=0 PAGES=1 DATAREQUESTS=0 SHOWCASES=1 DATASETS=1 OPENSTANDARDS=1 /usr/lib/ckan/default/bin/paster --plugin=ckanext-dgithree scripted_harvesters dgitwo --config=/etc/ckan/default/ckan.ini`
- [x] add db tables from production following steps here: https://github.com/derilinx/ckan-docker/issues/205 and here: https://github.com/derilinx/ckan-docker/issues/193
  - The tables we want are: `stats`, `datarequests`, `datarequests_comments`
- [x] run other scripted_harvesters
- [x] rebuild to set up the rest of the harvesters
- [x] `paster views create` at some point after all the datasets are in.
- [x] Feature the datasets that were featured on dgi2 by just going to the dataset and clicking featured
  - at time of writing it's RTPI, Oireachtas and National Planning Apps
- [x] Run each cron job manually (except harvesters)
- [ ] Update emails to send to dper, etc
- [ ] sync passwords from staging for usere who have changed them. 
- [ ] send reset password email again
Note:dce = docker-compose exec
